# @name get all courses - no authentication
GET http://{{domain}}/api/courses
Accept: application/json
Content-Type:application/json

###

# @name get all courses
GET http://{{domain}}/api/courses
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

# @name get all courses with all relations
GET http://{{domain}}/api/courses?populate=*
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

# @name get the category of all courses and sort by their id
GET http://{{domain}}/api/courses?populate[0]=category&sort[0]=id
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

# @name sort courses on id parameter
GET http://{{domain}}/api/courses?sort[0]=id
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

# @name get course by id
GET http://{{domain}}/api/courses/{{course_id}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

# @name get course by id and media link
GET http://{{domain}}/api/courses/{{course_id}}?populate[Content][populate][Media][fields][0]=url
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

# @name get course main media link
GET http://{{domain}}/{{media_link}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

# @name get all lessons of a course
GET http://{{domain}}/api/courses/{{course_id}}?populate[0]=lessons
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

# this kind of population is not performant and should be avoided
# @name get all topics populated from a course
GET http://{{domain}}/api/courses/{{course_id}}?populate[lessons][populate][0]=topics
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

# @name get all courses of a user
GET http://{{domain}}/api/courses/{{course_id}}?populate=[users]&filters[users][id][$eq]={{user_id}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

# @name register a user for a course
PUT http://{{domain}}/api/courses/{{course_id}}/register
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

# @name get course progress of an user
GET http://{{domain}}/api/user-course-progresses/{{course_id}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

# @name get course progress of an user
GET http://{{domain}}/api/user-lesson-states?api/user-topic-states?filters[$and][0][users_permissions_user][id][$eq]=16&filters[$and][1][lesson][id][$eq]=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

# @name get topic status of an user
GET http://{{domain}}/api/user-topic-states?filters[$and][0][users_permissions_user][id][$eq]=16&filters[$and][1][topic][id][$eq]=1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}
